DOCUMENT_TEXT = 'document_text'
LONG_ANSWER   = 'long_answer'
SHORT_ANSWER  = 'short_answers'
QUESTION_TEXT = 'question_text'
ANNOTATIONS   = 'annotations'
TOP_LEVEL     = 'top_level'
START_TOKEN   = 'start_token'
END_TOKEN     = 'end_token'
YES_NO        = 'yes_no_answer'
CANDIDATE_IDX = 'candidate_index'
LONG_ANSWER_CANDIDATES = 'long_answer_candidates'

train_file_path = '../simplified-nq-train.jsonl'
test_file_path  = '../simplified-nq-test.jsonl'

train_op_path = '../trainfile.json'
test_op_path  = '../testfile.json'
